### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cognitus** [lavers/g815-driver#1]
I wanna try this...   can you update the readme? how to install, requirements, options for config and stuff...

**Comment by lavers** [comment]
I've added some instructions to the readme, let me know if there's any other info you would find helpful :) I'm guessing you already solved your earlier issue with the feature flags - but I've also updated the code to no longer require the nightly channel as the few features I was using have now been stabilised.

**Comment by cognitus** [comment]
Finally i could try it... 

sadly, it crashed a lot 

```bash 
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/g815d`
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x0
  Serial number of failed request:  4183
  Current serial number in output stream:  4183

```
i had to create a bash script to restart every time it crashed, i don't know rust, maybe you could create a method to fallback when the windows is not found. 

~btw, I don't have problem that you describe with the media buttons, when the application crashed.~ update:  only happens when is used the volume wheel, but its different to what you describe, volume wheel is usuable but with a severe input lag  =/

apart of that , it worked great! 

an idea it would be great the rgb off automatic when the session or screen is off.
